// src/components/Project/Add.vue
<template>
    <el-dialog v-model="vis" title="新增项目">
        <el-form :model="form" :rules="formRule">
            <el-form-item label="项目名称" prop="name">
                <el-input v-model="form.name"></el-input>
            </el-form-item>
            <el-form-item label="项目路径" prop="path">
                <el-input readonly v-model="form.path">
                    <template #append>
                        <el-button @click="choose">选择</el-button>
                    </template>
                </el-input>

            </el-form-item>
        </el-form>
        <template #footer>
            <el-button @click="vis = false">取 消</el-button>
            <el-button type="primary" @click="yes">确 定</el-button>
        </template>
    </el-dialog>
</template>
<script setup>
import { reactive, ref } from 'vue'
import { chooseFolder } from "@/utils"
import { useProject } from '@/stores/counter';

const vis = ref(false)
const form = reactive({
    name: "",
    path: ""
})
const emit = defineEmits(['yes', 'register'])
const formRule = {
    name: [
        { required: true, message: '请输入项目名称', trigger: 'blur' },
        { min: 3, max: 12, message: '长度在 3 到 12 个字符', trigger: 'blur' }
    ],
    path: [
        { required: true, message: '请选择项目路径', trigger: 'blur' },
        { min: 3, max: 100, message: '长度在 3 到 100 个字符', trigger: 'blur' }
    ]
}
function open () {
    vis.value = true
}
function yes () {
    useProject().add(JSON.parse(JSON.stringify(form)))
    setTimeout(() => {
        form.name = ""
        form.path = ""
        vis.value = false
        emit("yes")
    }, 0);

}
function no () { }
function choose () {
    Promise.resolve(0).then(() => {
        chooseFolder().then(res => {
            if (res) {
                form.path = res[0]
            }

        })
    })
}
emit("register", {
    open
})
</script>
<style lang="scss" scoped>
</style>

// src/components/Project/Add.tsx
import { Button } from "antd";
import { Form, Input } from "antd";
import { Modal } from "antd";
import { useState, useEffect } from "react";
import { chooseFolder } from "@/utils";
import { PlusOutlined } from "@ant-design/icons";
export function addProject() {}
type FieldType = {
  name?: string;
  path?: string;
};
// type PropsType = {
//   ok: (p: { value: Record<string, any>; close: () => void }) => void;
// };
type PropsType = {
  ok: (value: Record<string, any>, close: () => void) => void;
};
export const AddProject = (props: PropsType) => {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [path, setPath] = useState("");
  const [formInstance] = Form.useForm();
  const showModal = () => {
    setIsModalOpen(true);
  };
  function _close() {
    setIsModalOpen(false);
  }
  const handleOk = () => {
    formInstance.submit();
  };
  const handleCancel = () => {
    setIsModalOpen(false);
  };
  function choose() {
    setTimeout(() => {
      chooseFolder().then(res => {
        if (res) {
          setPath(res[0]);
        }
      });
    }, 0);
  }
  const onFinish = v => {
    props.ok(v, _close);
  };
  useEffect(() => {
    formInstance.setFields([{ name: "path", value: path }]);
    return () => {};
  }, [path]);
  useEffect(() => {
    formInstance.resetFields();
    setPath("");
    return () => {};
  }, [isModalOpen]);
  return (
    <>
      <Button icon={<PlusOutlined />} type="link" onClick={showModal}></Button>
      <Modal
        title="新增项目"
        open={isModalOpen}
        onOk={handleOk}
        onCancel={handleCancel}
      >
        <Form
          form={formInstance}
          name="basic"
          labelCol={{ span: 4 }}
          wrapperCol={{ span: 20 }}
          style={{ maxWidth: 600 }}
          initialValues={{ remember: true }}
          onFinish={onFinish}
          autoComplete="off"
        >
          <Form.Item<FieldType>
            label="项目路径"
            name="path"
            rules={[{ required: true, message: "请选择项目路径!" }]}
          >
            <Input readOnly addonAfter={<span onClick={choose}>选择</span>} />
          </Form.Item>
          <Form.Item<FieldType>
            label="名称"
            name="name"
            rules={[{ required: true, message: "请输入项目名称！" }]}
          >
            <Input />
          </Form.Item>
        </Form>
      </Modal>
    </>
  );
};
